apiVersion: v1
kind: Secret
metadata:
  name: ldap-browser-secret
  namespace: ldap-browser
  labels:
    app: ldap-browser
type: Opaque
stringData:
  APP_PORT: "8080"
  APP_AUTH_ENABLED: "false"
  APP_AUTH_USERNAME: "admin"
  APP_AUTH_PASSWORD: "changeme"

# Made with Bob