apiVersion: v1
kind: Service
metadata:
  name: ldap-browser
  namespace: ldap-browser
  labels:
    app: ldap-browser
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ldap-browser

# Made with Bob
