name: LDAP Browser Lab container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - '**'
      - '!lab*.sh'
      - '!**.adoc'
      - '!**.md'
      - '!openshift/**'
jobs:
  postgresql-lab-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/ldap-browser
      tagname: $GITHUB_REF_NAME
      dockerfile: Dockerfile
      directory: .
    secrets: inherit